version: "3.9"

services:
  app:
    build:
      context: .
    ports: ["8000:8000"]
    volumes:
      - ./phone_book_api:/phone_book_api
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

 